font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0
cursor_shape block
shell_integration no-cursor

enable_audio_bell no
enabled_layouts splits,stack,grid

map ctrl+shift+0 restore_font_size
map ctrl+c copy_or_interrupt

# Phím tắt chia màn hình (Ngang: Ctrl+Shift+- | Dọc: Ctrl+Shift+|)
map ctrl+shift+minus launch --location=hsplit
map ctrl+shift+backslash launch --location=vsplit

# Phóng to / Thu nhỏ ô hiện tại (Zoom tương tự tmux prefix+z)
map ctrl+shift+z toggle_layout stack
# Phím tắt co giãn ô trực tiếp (Ngang: Ctrl+Alt+h/l | Dọc: Ctrl+Alt+j/k)
map ctrl+alt+h resize_window narrower 3
map ctrl+alt+l resize_window wider 3
map ctrl+alt+k resize_window taller 3
map ctrl+alt+j resize_window shorter 3

# Phím tắt chuyển đổi tiêu điểm (Focus) theo hướng Vim (Alt + h/j/k/l)
map alt+h neighboring_window left
map alt+l neighboring_window right
map alt+k neighboring_window up
map alt+j neighboring_window down

window_padding_width 0 2
hide_window_decorations yes
confirm_os_window_close 0

allow_remote_control yes

listen_on unix:/tmp/mykitty

background_opacity 0.85

include current_theme.conf
