# WHY: JetBrains Mono provides optimal legibility for coding with ligatures support
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

# HACK: Disables the annoying audio bell
enable_audio_bell no

# PERF: UI Spacing and Window borders
window_padding_width 15
hide_window_decorations yes
confirm_os_window_close 0

# WHY: Injects the Alpha Channel for Hyprland to process the Kawase Blur
background_opacity 0.85

# TODO: Include the exact color palette to match the system theme
include theme.conf
