general {
    disable_loading_bar = true
    grace = 0
    hide_cursor = true
    fail_timeout = 2000
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.02
    contrast = 1.15
    brightness = 0.5
    vibrancy = 0.0
    vibrancy_darkness = 1.0
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    font_size = 120
    font_family = JetBrainsMono Nerd Font Bold
    color = rgb(f5f5f5)
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date '+%A, %d %B')"
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    color = rgb(888888)
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    
    outer_color = rgb(d50000)
    inner_color = rgb(000000)
    font_color = rgb(f5f5f5)
    
    fade_on_empty = false
    placeholder_text = <span foreground="##888888">Enter Credentials...</span>
    
    check_color = rgb(f5f5f5)
    fail_color = rgb(d50000)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    
    capslock_color = rgb(f5f5f5)
}

label {
    monitor =
    text = $USER
    font_size = 14
    font_family = JetBrainsMono Nerd Font Bold
    color = rgb(f5f5f5)
    position = 0, 45
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:500] ~/.config/hypr/scripts/mpris.sh
    font_size = 12
    font_family = JetBrainsMono Nerd Font Italic
    color = rgb(888888)
    position = 0, -150
    halign = center
    valign = center
}
