--ozone-platform-hint=auto
--enable-wayland-ime
--wayland-text-input-version=3
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--canvas-oop-rasterization
--disable-features=ExtensionManifestV2Unsupported,ExtensionManifestV2Disabled
--enable-native-gpu-memory-buffers
--render-node-override=/dev/dri/renderD128
--enable-features=VaapiVideoDecoder,AcceleratedVideoEncoder,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
