hl.on("hyprland.start", function()
  hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
  hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
  hl.exec_cmd("waybar")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("fcitx5 -d")
  hl.exec_cmd("swaync")
  -- hl.exec_cmd("nm-applet")
  -- hl.exec_cmd("blueman-applet")
  hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
end)
