hl.on("hyprland.start", function()
  hl.exec_cmd("nm-applet")
  hl.exec_cmd("waybar & hyprpaper")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd("fcitx5 -d")
  hl.exec_cmd("swaync")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
end)
